load("@com_github_schoppmp_rules_oblivc//oblivc:oblivc.bzl", "oblivc_library")

oblivc_library(
    name = "sigmoid",
    srcs = [
        "sigmoid.oc",
    ],
    hdrs = [
        "sigmoid.h",
    ],
    visibility = ["//visibility:public"],
)
