package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "time",
    srcs = ["time.c"],
    hdrs = ["time.h"],
)

cc_library(
    name = "serialize_le",
    hdrs = ["serialize_le.hpp"],
)
